var lang = {
	"lang_code": "de",
	"title": "Vorratsdatenspeicherung in der Schweiz",
	"town_zuerich": "Zürich",
	"town_bern": "Bern",
	"town_basel": "Basel",
	"town_genf": "Genf",
	"town_luzern": "Luzern",
	"town_lausanne": "Lausanne",
	"weekday_short_mon": "Mo",
	"weekday_short_tue": "Di",
	"weekday_short_wed": "Mi",
	"weekday_short_thu": "Do",
	"weekday_short_fri": "Fr",
	"weekday_short_sat": "Sa",
	"weekday_short_sun": "So",
	"msg_type_fb": "Facebook-Post",
	"msg_type_tw": "Tweet",
	"msg_type_sm": "SMS %",
	"msg_type_ca": "Anruf %",
	"msg_type_ma": "E-Mail %",
	"word_from": "von",
	"word_to": "an",
	"word_From": "Von",
	"word_To": "An",
	"word_Content": "Inhalt",
	"word_number": "Nr.",
	"social_info_name": "Name",
	"social_info_org": "Gruppe",
	"social_info_email_out": "E-Mails an Balthasar",
	"social_info_email_in": "E-Mails von Balthasar",
	"social_info_email_co": "im CC von E-Mails an Balthasar:",
	"social_info_sms_out": "SMS an Balthasar",
	"social_info_sms_in": "SMS von Balthasar",
	"social_info_call_out": "Telefonate an Balthasar",
	"social_info_call_in": "Telefonate von Balthasar",
	"social_info_maincomtimes": "Hauptkommunikationszeiten",
	"contact_adlethorensgoumaz": "Adèle Thorens Goumaz",
	"contact_arztrztin": "Arzt/Ärztin",
	"contact_assistentin": "Assistent/in",
	"contact_asylchmailingliste": "asyl.ch-Mailingliste",
	"contact_asylchnewsletter": "asyl.ch-Newsletter",
	"contact_balthasarglttli": "Balthasar Glättli",
	"contact_brigittemarti": "Brigitte Marti",
	"contact_bundesrat": "Bundesrat",
	"contact_digigesmailingliste": "digiges-Mailingliste",
	"contact_diverse": "Diverse",
	"contact_doodlenewsletter": "doodle-Newsletter",
	"contact_facebooknewsletter": "Facebook-Newsletter",
	"contact_factschnewsletter": "facts.ch-Newsletter",
	"contact_familie": "Familie",
	"contact_gemeinderat": "Gemeinderat",
	"contact_googlealerts": "Google Alerts",
	"contact_googlecalendar": "Google Calendar",
	"contact_googlenewsletter": "Google-Newsletter",
	"contact_grne": "Grüne",
	"contact_hyperalertsnewsletter": "hyperalerts-Newsletter",
	"contact_journalistin": "Journalist/in",
	"contact_kantonsrat": "Kantonsrat",
	"contact_medien": "Medien",
	"contact_mediendienstezuerichch": "mediendienste@zuerich.ch",
	"contact_minlimartipartnerin": "Min Li Marti (Partnerin)",
	"contact_miriambehrens": "Miriam Behrens",
	"contact_mutter": "Mutter",
	"contact_nationalrat": "Nationalrat",
	"contact_netzwochechnewsletter": "netzwoche.ch-Newsletter",
	"contact_newsadminchnewsletter": "news.admin.ch-Newsletter",
	"contact_newsaktuellch": "newsaktuell.ch",
	"contact_ngo": "NGO",
	"contact_ngomieterrecht": "NGO Mieterrecht",
	"contact_ngomigrationasyl": "NGO Migration/Asyl",
	"contact_nzznewsletter": "NZZ-Newsletter",
	"contact_parlamentarierin": "Parlamentarier/in",
	"contact_parlamentsnewsletter": "Parlaments-Newsletter",
	"contact_person": "Person",
	"contact_pfarrer": "Pfarrer",
	"contact_politik": "Politik",
	"contact_politnetznewsletter": "Politnetz-Newsletter",
	"contact_rechtsanwalt": "Rechtsanwalt",
	"contact_ronorpnetnewsletter": "ronorp.net-Newsletter",
	"contact_sonstigerkontakt": "Sonstiger Kontakt",
	"contact_stadtrat": "Stadtrat",
	"contact_stnderat": "Ständerat",
	"contact_swissconsortiumnewsletter": "swissconsortium-Newsletter",
	"contact_tamedianewsletter": "Tamedia-Newsletter",
	"contact_twitter": "Twitter",
	"contact_uelileuenberger": "Ueli Leuenberger",
	"contact_universitt": "Universität",
	"contact_vater": "Vater",
	"contact_verteiler": "Verteiler",
	"contact_wordpresscomnewsletter": "wordpress.com-Newsletter",
	"contact_xingcomnewsletter": "xing.com-Newsletter"
}