var lang = {
	"lang_code": "en",
	"lang_name": "English",
	"title": "Data retention in Switzerland",
	"town_zuerich": "Zurich",
	"town_bern": "Bern",
	"town_basel": "Basel",
	"town_genf": "Geneva",
	"town_luzern": "Lucerne",
	"town_lausanne": "Lausanne",
	"weekday_short_mon": "Mon",
	"weekday_short_tue": "Tue",
	"weekday_short_wed": "Wed",
	"weekday_short_thu": "Thu",
	"weekday_short_fri": "Fri",
	"weekday_short_sat": "Sat",
	"weekday_short_sun": "Sun",
	"msg_type_fb": "Facebook post",
	"msg_type_tw": "Tweet",
	"msg_type_sm": "SMS %",
	"msg_type_ca": "Call %",
	"msg_type_ma": "Email %",
	"word_from": "from",
	"word_to": "to",
	"word_From": "From",
	"word_To": "To",
	"word_Content": "Content",
	"word_number": "No.",
	"social_info_name": "Name",
	"social_info_org": "Group",
	"social_info_email_out": "Emails to Balthasar",
	"social_info_email_in": "Emails from Balthasar",
	"social_info_email_co": "In CC of E-Mails to Balthasar",
	"social_info_sms_out": "SMS to Balthasar",
	"social_info_sms_in": "SMS from Balthasar",
	"social_info_call_out": "Calls to Balthasar",
	"social_info_call_in": "Calls from Balthasar",
	"social_info_maincomtimes": "Main time of communication",
	"contact_adlethorensgoumaz": "Adèle Thorens Goumaz",
	"contact_arztrztin": "Doctor",
	"contact_assistentin": "Assistant",
	"contact_asylchmailingliste": "asyl.ch mailing list",
	"contact_asylchnewsletter": "asyl.ch newsletter",
	"contact_balthasarglttli": "Balthasar Glättli",
	"contact_brigittemarti": "Brigitte Marti",
	"contact_bundesrat": "Federal Council",
	"contact_digigesmailingliste": "digiges mailing list",
	"contact_diverse": "miscellaneous",
	"contact_doodlenewsletter": "doodle newsletter",
	"contact_facebooknewsletter": "Facebook newsletter",
	"contact_factschnewsletter": "facts.ch newsletter",
	"contact_familie": "Family",
	"contact_gemeinderat": "Local council",
	"contact_googlealerts": "Google Alerts",
	"contact_googlecalendar": "Google Calendar",
	"contact_googlenewsletter": "Google newsletter",
	"contact_grne": "The Greens",
	"contact_hyperalertsnewsletter": "hyperalerts newsletter",
	"contact_journalistin": "Journalist",
	"contact_kantonsrat": "Canton council",
	"contact_medien": "Media",
	"contact_mediendienstezuerichch": "mediendienste@zuerich.ch",
	"contact_minlimartipartnerin": "Min Li Marti (partner)",
	"contact_miriambehrens": "Miriam Behrens",
	"contact_mutter": "Mother",
	"contact_nationalrat": "National Council",
	"contact_netzwochechnewsletter": "netzwoche.ch newsletter",
	"contact_newsadminchnewsletter": "news.admin.ch newsletter",
	"contact_newsaktuellch": "newsaktuell.ch",
	"contact_ngo": "NGO",
	"contact_ngomieterrecht": "NGO tenant-right",
	"contact_ngomigrationasyl": "NGO migration/asylum",
	"contact_nzznewsletter": "NZZ newsletter",
	"contact_parlamentarierin": "Member of Parliament",
	"contact_parlamentsnewsletter": "Parliament newsletter",
	"contact_person": "Person",
	"contact_pfarrer": "Priest",
	"contact_politik": "Politics",
	"contact_politnetznewsletter": "Politnetz newsletter",
	"contact_rechtsanwalt": "Lawyer",
	"contact_ronorpnetnewsletter": "ronorp.net newsletter",
	"contact_sonstigerkontakt": "Other contact",
	"contact_stadtrat": "City Council",
	"contact_stnderat": "Council of States",
	"contact_swissconsortiumnewsletter": "swissconsortium newsletter",
	"contact_tamedianewsletter": "Tamedia newsletter",
	"contact_twitter": "Twitter",
	"contact_uelileuenberger": "Ueli Leuenberger",
	"contact_universitt": "University",
	"contact_vater": "Father",
	"contact_verteiler": "Mailing list",
	"contact_wordpresscomnewsletter": "wordpress.com newsletter",
	"contact_xingcomnewsletter": "xing.com newsletter"
}