var lang = {
	"lang_code": "de",
	"title": "Vorratsdatenspeicherung in der Schweiz",
	"town_zuerich": "Zürich",
	"town_bern": "Bern",
	"town_basel": "Basel",
	"town_genf": "Genf",
	"town_luzern": "Luzern",
	"town_lausanne": "Lausanne",
	"weekday_short_mon": "Mo",
	"weekday_short_tue": "Di",
	"weekday_short_wed": "Mi",
	"weekday_short_thu": "Do",
	"weekday_short_fri": "Fr",
	"weekday_short_sat": "Sa",
	"weekday_short_sun": "So",
	"msg_type_fb": "Facebook-Post",
	"msg_type_tw": "Tweet",
	"msg_type_sm": "SMS %",
	"msg_type_ca": "Anruf %",
	"msg_type_ma": "E-Mail %",
	"word_from": "von",
	"word_to": "an",
	"word_From": "Von",
	"word_To": "An",
	"word_Content": "Inhalt",
	"word_number": "Nr.",
	"social_info_name": "Name",
	"social_info_org": "Gruppe",
	"social_info_email_out": "E-Mails an Balthasar",
	"social_info_email_in": "E-Mails von Balthasar",
	"social_info_email_co": "im CC von E-Mails an Balthasar:",
	"social_info_sms_out": "SMS an Balthasar",
	"social_info_sms_in": "SMS von Balthasar",
	"social_info_call_out": "Telefonate an Balthasar",
	"social_info_call_in": "Telefonate von Balthasar",
	"social_info_maincomtimes": "Hauptkommunikationszeiten"
}